### ISSUE TITLE
DG: Planned enhancements

### ISSUE THREAD

**Issue by tituschewxj** [AY2324S2-CS2103T-F13-1/tp#241]
**Planned enhancements list**
- [x] 1. See #249 (this needs to be spilt into 2)
- [x] 2. Improve validation checking for names. See #214, #180
- [x] 3. Not all email formats are permitted. See https://en.wikipedia.org/wiki/Email_address#Valid_email_addresses
- [x] 4. See #187
- [x] 5. See #175 
- [x] 6. See #198
- [x] 8. (Suggestion) Improving find to work on all attributes. (as right now it is limited to only name) (we cannot add all attributes easily, so the trade off is to just add for week number)
- [ ] 12. (suggestion) I realised a feature flaw in our command history retrieval, which is that we should save our current input as the most recent command, rather than erasing it. (this is low)
- [ ] 11. (Suggestion) improve student card display of attendance (this is low) (in fact by adding find filtering by week number, this is very low)
- [ ] 9. Add validation for find command, see #195 (not that important - does not impact user -> very low/out of scope?)
- [ ] 7. (Suggestion) We may want to improve the parsing of certain attributes, as it is a limitation that unrecognized prefixes cannot be parsed. (not in scope)
- [ ] ~~10. (Suggestion) Add grades feature: (Omitted: Each enhancement should be a tweak to an existing feature, and should not be a new feature altogether.)~~ (not in scope)

### Misc info

 We highly recommend adding an appendix named Planned Enhancements, listing fixes you propose to add in the near future, to counter known feature flaws.
* This section may contain up to team_size x 2 enhancements e.g., a 5-person team can have up to 10 enhancements.
* At the start of the section, clearly state the team size. While this information is not useful for a real DG, it will help PE testers easily see if you have exceeded the allowed planned enhancements count.
For a similar reason, structure this section as a numbered list, each item in the list describing exactly one planned enhancement.
* Each enhancement should be specific, describing the feature flaw it addresses and how exactly the feature will be changed, providing sample UIs/inputs/outputs if applicable. e.g.,
Planned Enhancements
* Each enhancement should be a tweak to an existing feature, and should not be a new feature altogether.
type.FeatureFlaw bug reports matching an item in this section will not be penalized for the team, and testers will not earn credit for reporting them either. However, testers can report type.FeatureFlaw bugs on the enhancements listed in this section, if they think the planned feature tweak itself is flawed/inadequate.
* FAQ: Enhancement X and Y are very similar. Can we count them as one?
Answer: Only if adding one automatically adds the other. If one can be added without the other, they are counted as two enhancements.
* If the team has exceeded the allowed count in the planned enhancements, only the first N items (where N is team size x 2) in that list will have immunity. The rest can be reported as bugs. In addition, exceeding the count can be reported as a separate DG bug.

**Comment by belligerentbeagle** [comment]
Adding another planned enhancement:
- [ ] 6. Make phone number and email address unique, See #198
