### ISSUE TITLE
UG: misc changes

### ISSUE THREAD

**Issue by tituschewxj** [AY2324S2-CS2103T-F13-1/tp#252]
**Compilation of Misc changes:**  (can add on here instead of creating a new issue entirely, and we can create issues from here using `Convert to issue`)
- [x] add in the known issues section that opening multiple copies of TAPro will cause the data to desync. See #187
- [x] Use caps for `JAR`.
- [x] Remove redundant bolded Tip:/Note: in a box.
- [x] Update keyboard button style to :`<span class="badge bg-light text-dark border">Tab</span>`. Make into macro. See #270
- [x] Add note that in help window, the nusnet id is in lowercase, but it still works.
- [x] Add note to major that multiple majors can be added, using commas to separate them.
- [x] Add note that s/o and d/o is not permitted in name and provide a workaround (in addstu). See #214
- [x] #266
- [x] #265
- [x] Add at least one screenshot for each command. See #209 , #158
  - [x] Screenshots need to be resized, #232 did not correctly resize the image.
- [x] Make it clear that the courses being taught are CS courses. See #164
- [x] #259
- [x] Add acknowledgements for dev-dependencies used.
- [x] Up down keys in DG not correct format
- [x] Ui.png is wrong. refer to https://nus-cs2103-ay2324s2.github.io/website/schedule/week13/project.html
- [x] PPP.page should be github username
- [x] Proof read UG/DG
- [x] Change priorities to must have, should have and nice to have.
- [x] Add note that there must be a space before each prefix
- [x] check if all cs2101 ug things are there
- [ ] #327
- [ ] ~~Add syntax highlighting feature?~~ (not important: as it is not a standalone feature)
- [ ] ~~Add note that names must be english names~~ (implied)
- [ ] ~~For mark/unmark/delstu, we need to specify that only the last value specified for each parameter would be accepted. (as there are no duplicate prefix checks)~~ (in planned enhancements)
- [ ] ~~Add note that certain email addresses are not allowed, and the valid email addresses follow the validation format of popular email service providers, such as gmail, which doesn't allow consequtive symbols (.-_). See: https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/215#issuecomment-2050891984~~ (in planned enhancements)
- [ ] ~~Add copy button to code snippets.~~

**Comment by belligerentbeagle** [comment]
> * [ ]  Add note that s/o and d/o is not permitted in name and provide a workaround (in addstu). See [[PE-D][Tester D] FeatureFlaw: name field does not allow S/O and D/O #214](https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/214)
> *

Remove this since we would no longer have name validation? @tituschewxj
